apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend2product-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend2product-backend
  template:
    metadata:
      labels:
        app: trend2product-backend
    spec:
      containers:
      - name: backend
        image: yourdockerhub/trend2product-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NOTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: trend2product-secrets
              key: NOTION_TOKEN
        # Add other secrets/env vars here
