apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-product-api
  template:
    metadata:
      labels:
        app: trend-product-api
    spec:
      containers:
        - name: api
          image: your-dockerhub-username/trend-product-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: TWITTER_BEARER
              valueFrom:
                secretKeyRef:
                  name: trend-product-secrets
                  key: TWITTER_BEARER
            # add other env secrets here
