apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend2product-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend2product-mongo
  template:
    metadata:
      labels:
        app: trend2product-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
