version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TWITTER_BEARER=${TWITTER_BEARER}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY}
      - MAILCHIMP_SERVER_PREFIX=${MAILCHIMP_SERVER_PREFIX}
      - GUMROAD_ACCESS_TOKEN=${GUMROAD_ACCESS_TOKEN}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - FINANCE_API_KEY=${FINANCE_API_KEY}

  airflow:
    image: apache/airflow:2.6.3
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
