name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v3
      with:
        context: ./src/backend
        push: true
        tags: yourdockerhub/trend2product-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v3
      with:
        context: ./src/dashboard/frontend
        push: true
        tags: yourdockerhub/trend2product-frontend:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.26.0

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy via Helm
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        helm upgrade --install trend2product ./trend2product --namespace default
